<?php
$config['full_tag_open']= '<p id="pagination">';
$config['full_tag_close']= '</p>';
$config['first_link'] 	= 'First';
$config['first_tag_open'] = '<span class="pagination_link">';
$config['first_tag_close'] = '</span>';
$config['last_link'] 	= 'Last';
$config['last_tag_open'] = '<span class="pagination_link">';
$config['last_tag_close'] = '</span>';
$config['next_link'] 	= 'Next';
$config['next_tag_open'] = '<span class="pagination_link">';
$config['next_tag_close'] = '</span>';
$config['prev_link'] 	= 'Prev';
$config['prev_tag_open'] = '<span class="pagination_link">';
$config['prev_tag_close'] = '</span>';
$config['cur_tag_open'] = '<span class="current_link"><strong>';
$config['cur_tag_close'] = '</strong></span>';
$config['num_tag_open'] = '<span class="digit_link">';
$config['num_tag_close'] = '</span>';
$config['num_links'] = 10;
